export const USER_REGISTERED = "USER_REGISTERED"
export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"

export const FETCHED_PLACES = "FETCHED_PLACES"
export const FETCHED_RECOMMENDED_PLACES = "FETCHED_RECOMMENDED_PLACES"
export const FETCHED_PLACE = "FETCHED_PLACE"
export const FETCHED_SCHEDULES = "FETCHED_SCHEDULES"
export const CREATED_PLACE = "CREATED_PLACE"

export const USER_UPDATED = "USER_UPDATED"

export const SHOW_FLASH = "SHOW_FLASH"
export const SHOW_ERROR = "SHOW_ERROR"
export const CREATE_ERROR = "CREATE_ERROR"
export const UPDATE_ERROR = "UPDATE_ERROR"
export const HIDE_FLASH = "HIDE_FLASH"

export const APOLLO_QUERY_RESULT = "APOLLO_QUERY_RESULT"
