export const USER_REGISTERED = "USER_REGISTERED";
export const LOGGED_IN = "LOGGED_IN";
export const LOGGED_OUT = "LOGGED_OUT";

export const FETCHED_PLACES = "FETCHED_PLACES";
export const FETCHED_RECOMMENDED_PLACES = "FETCHED_RECOMMENDED_PLACES";
